#! /bin/sh

sxhkd &

bspc monitor -d web term chat code music 6 7

bspc config border_width         0
bspc config window_gap          24

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# polybar
$HOME/.config/polybar/polybar.sh
